swagger: "2.0"
info:
  version: "1.0"
  title: "Parceldaily"
  # license:
  #   name: MIT
  #   url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
  description: |

    ParcelDaily API is a RESTful API for creating the **`order`** until displaying the **`status order`**. 
    ParcelDaily also provide the calculation of order price for every parcel. You can refer to `https://github.com/Auronex/parceldaily-api-doc` to read more about integration guideline and info.

    ### Important Integration Requirement

    Please take note of the following points:

      * We require shippers to cache the **`Token`** and **`Merchant Id`** for their API integration.
      * We suggest shippers to cache the downloaded consignment note as well. Please let our sales team know if you are not caching the consignment note at your end.
      * **`Token`** and **`Merchant Id`** can get in user profile
      * Shippers are encouraged to retry order creation requests IF a **HTTP 5xx** error is returned from our API
      * If a **HTTP 4xx** error is returned, please log the response for your debugging purposes.
        * **Do not** retry the same order creation request without fixing the error specified in the response
      * Minimum for pickup:
        * Poslaju: No Pick up for now
        * DHL: 5 parcels and above
        * NinjaVan: 1 parcels and above
        * J&T: 5 parcels and above
        * Citylink: 1 parcels and above
        * Pickupp: 1 parcels and above
      * This API documentation is at version 1.0, we are always in a process of making our API more developer friendly as we all are developer. If you find any error message is not descriptive or missing error message, please send an email to **<sales@parceldaily.com>**


    _**NOTE**_: Please contact your account manager to assign a Sandbox **`Token`** and **`Merchant Id`** for your account. If you are here for play around, you can try use this credential for quick test purpose. 

    | Merchant Id | Token  |
    | ----------- | ------------ |
    | 8VqGyrqYCQ  | 950af98c-f033-4cdd-ae8a-82db543a3efe |

    ### Base URL By Environment

    | Environment | Base URL  |
    | ----------- | --------- |
    | Production  | https://api.parceldaily.com |
    | Sandbox     | https://api.sandbox.parceldaily.com |

    ### Tracking API

    We provide a webhook API only for for **POST** method for tracking of parcels. More information available [here](https://github.com/Auronex/parceldaily-api-doc).

host: api.sandbox.parceldaily.com
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/partner/postcode:
    x-summary: Check state
    post:
      description: >-
        Get the state of a postcode in Malaysia
      summary: POST
      parameters:
        - name: token
          in: header
          description: a account secret
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/PostcodeRequest"
      responses:
        200:
          description: "Successfully Responses result"
          schema:
            $ref: "#/definitions/Postcode"
          examples:
            application/json:
              success:
                ok: true
                state: "Pahang"
        401:
          description: "Unauthorized Responses result"
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Unauthorized"
              message: "Secret key must be provided"

  /v1/partner/merchant/quote:
    x-summary: Rate Checking
    post:
      description: |
        Get the quote of a order. This API will return different rate depending your user/package tier. Please refer to sales team for more information about the rate

        _**NOTE**_: Please take note that if the **`price`** value did'nt show or value is **`0`**, its mean that parcel do not support that postcode
      summary: POST
      parameters:
        - name: token
          in: header
          description: a account secret
          required: true
          type: string
        - name: merchantid
          in: header
          description: a account id
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/QuoteRequest"
      responses:
        200:
          description: "Successfully Responses result"
          schema:
            $ref: "#/definitions/Quote"
          examples:
            application/json:
              success:
                fromPostcode:
                  Postcode: 25200
                  Place: "Bandar Indera Mahkota"
                  Area: "Kuantan"
                  State: "PHG"
                  StateName: "Pahang"
                  CountryName: "Malaysia"
                toPostcode:
                  Postcode: 25200
                  Place: "Bandar Indera Mahkota"
                  Area: "Kuantan"
                  State: "PHG"
                  StateName: "Pahang"
                  CountryName: "Malaysia"
                poslajuPrice: "10.00"
                poslajuPostage: "10.00"
                cod: 0
                notificationRate: ""
                dhlPrice: "6.50"
                dhlCod: ""
                dhlInsurance: ""
                dhlPostage: "6.50"
                ninjavanPrice: "9.00"
                ninjavanCod: ""
                ninjavanInsurance: ""
                ninjavanPostage: "9.00"
                jntPrice: "8.00"
                jntCod: ""
                jntInsurance: ""
                jntPostage: "8.00"
                citylinkPostage: "9.00"
                citylinkPrice: "9.00"
                pickuppPostage: ""
                pickuppCod: ""
                pickuppPrice: ""
                teleportPostage: ""
                teleportCod: ""
                teleportPrice: ""
                sfstandardPostage: ""
                sfstandardPrice: ""
                sfeconomyPostage: ""
                sfeconomyPrice: ""
                flashPostage: "8.00"
                flashCod: ""
                flashPrice: "8.00"

        422:
          description: "Empty value Responses result"
          schema:
            $ref: "#/definitions/ErrorEmpty"
          examples:
            application/json:
              error:
                {
                  destination:
                    [
                      "Should not be empty",
                      "Does not fulfill requirement: isLength",
                    ],
                }
        401:
          description: "Unauthorized Responses result"
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Unauthorized"
              message: "Secret key must be provided"

  /v1/partner/order/create:
    x-summary: Create Order
    post:
      description: |
        Creates a new order. When a order is create, it means added into cart. You will need to call Checkout API to checkout the order. 

        _**NOTE**_: Please take note that the **`price`** value must be same with the checking price API and parcel **`jnt`** didnt provide for sandbox
      summary: POST
      parameters:
        - name: token
          in: header
          description: a account secret
          required: true
          type: string
        - name: merchantid
          in: header
          description: a account id
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/CreateOrderRequest"
      responses:
        200:
          description: "Successfully Responses result"
          schema:
            $ref: "#/definitions/CreateOrder"
          examples:
            application/json:
              success:
                {
                  serviceProvider: "dhl",
                  merchant:
                    {
                      name: "Auronex ",
                      BRN: "002074755",
                      memberType: "Normal",
                      package:
                        {
                          __type: "Pointer",
                          className: "Package",
                          objectId: "KNPjuvbgHo",
                        },
                      createdAt: "2020-11-24T07:39:59.033Z",
                      updatedAt: "2021-04-20T03:37:32.656Z",
                      phone: "0179339876",
                      bankName: "Maybank",
                      bankAccount: "7125642365",
                      totalTopup: 3,
                      credits: 53208.6,
                      objectId: "scsMoA9S1N",
                      __type: "Object",
                      className: "Merchant",
                    },
                  price: 6.5,
                  content_value: 2,
                  receiver:
                    {
                      email: "ahmad@gmail.com",
                      merchant:
                        {
                          __type: "Pointer",
                          className: "Merchant",
                          objectId: "scsMoA9S1N",
                        },
                      city: "Kuantan",
                      postcode: "25200",
                      phone: "60125875469",
                      state: "Pahang",
                      fullName: "ahmad",
                      line1: "No.10, Jalan Besar 12,",
                      line2: "Taman E",
                      createdAt: "2020-11-24T08:20:03.924Z",
                      updatedAt: "2020-12-23T13:04:00.596Z",
                      objectId: "ZgM2i48XNF",
                      __type: "Object",
                      className: "ClientAddress",
                    },
                  content: "2",
                  kg: 2,
                  cod: null,
                  pickup:
                    {
                      merchant:
                        {
                          __type: "Pointer",
                          className: "Merchant",
                          objectId: "scsMoA9S1N",
                        },
                      email: "wanmuhdamin@gmail.com",
                      city: "Kuantan",
                      postcode: "25200",
                      phone: "60135785469",
                      state: "Pahang",
                      fullName: "Wan",
                      line1: "No.12, Lororng IM12/16,",
                      line2: "Taman Alam Perdana",
                      createdAt: "2020-11-24T08:20:03.718Z",
                      updatedAt: "2021-04-09T11:50:18.645Z",
                      objectId: "3G4KCnNw9f",
                      __type: "Object",
                      className: "Address",
                    },
                  createdAt: "2021-04-20T04:15:24.225Z",
                  updatedAt: "2021-04-20T04:15:24.225Z",
                  objectId: "ykBc5wQuWw",
                }
        422:
          description: "Server calculated price does not match submitted price"
          examples:
            application/json:
              error: {}
        401:
          description: "Unauthorized Responses result"
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Unauthorized"
              message: "Secret key must be provided"

  /v1/partner/order/bulkCreate:
    x-summary: Create Bulk Order
    post:
      description: |
        Creates a new bulk order. When a order is create, it means added into cart. You will need to call Checkout API to checkout the order.

        _**NOTE**_: Please take note that the **`price`** value must be same with the checking price API and parcel **`jnt`** didnt provide for sandbox
      summary: POST
      parameters:
        - name: token
          in: header
          description: a account secret
          required: true
          type: string
        - name: merchantid
          in: header
          description: a account id
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/CreateBulkOrderRequest"
      responses:
        200:
          description: "Successfully Responses result"
          schema:
            $ref: "#/definitions/CreateBulkOrder"
          examples:
            application/json:
              success: ["aRG2YKxltx", "C4iFNBzXeW"]
        422:
          description: "Server calculated price does not match submitted price"
          examples:
            application/json:
              error: {}
        401:
          description: "Unauthorized Responses result"
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Unauthorized"
              message: "Secret key must be provided"

  /v1/partner/order/payAll:
    x-summary: Checkout Order
    post:
      description: |
        Making payment for the selected order. Please make sure you have enough credit in the wallet for better integration.

         _**NOTE**_: Please take note that **`DHL`** take some time to success compare with other courier and auto **`refund`** will trigger if order fail
      summary: POST
      parameters:
        - name: token
          in: header
          description: a account secret
          required: true
          type: string
        - name: merchantid
          in: header
          description: a account id
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/PayOrderRequest"
      responses:
        200:
          description: "Successfully Responses result"
          schema:
            $ref: "#/definitions/PayOrder"
          examples:
            application/json:
              success: [{ "orderId": "sfMeOuzvtK", "connote": "63125215258MY" }]
        500:
          description: "Object not found"
          examples:
            application/json:
              error: { message: "Object not found.", code: 101 }
        401:
          description: "Unauthorized Responses result"
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Unauthorized"
              message: "Secret key must be provided"

  /v1/partner/orders:
    x-summary: Get all orders
    get:
      description: >-
        Get all purchases order and their description.
      summary: GET
      parameters:
        - name: token
          in: header
          description: a account secret
          required: true
          type: string
        - name: merchantid
          in: header
          description: a account id
          required: true
          type: string
      responses:
        200:
          description: "Successfully Responses result."
          examples:
            application/json:
              orders:
                [
                  {
                    consignNote: "5520120314210252",
                    name: "Auronex",
                    receiver: "Jonny",
                    pickup: "Alex",
                    pickupEmail: "test@example.com",
                    content: "item",
                    receiverAddress:
                      {
                        line1: "No 5, Jalan Impian 4",
                        city: "Selangor",
                        postcode: "47000",
                        phone: "60120101010",
                      },
                    pickupAddress:
                      {
                        line1: "No.12, Lororng I 2/1,",
                        line2: "Taman A",
                        city: "Kuantan",
                        postcode: "25200",
                      },
                    orderId: "GSP5EcMGg6",
                    orderStatus: "Waiting Pickup",
                    orderLastUpdateStatus: "2021-03-18T18:10:54.713Z",
                    orderLastUpdateStatusDiffDay: 31,
                    kg: 5,
                    price: 19.3,
                    cod: 50,
                    paid: true,
                    serviceProvider: "dhl",
                    archived: "",
                    createdAt: "2021-03-18T12:45:43.016Z",
                    weight: 5,
                    receiverState: "Selangor",
                    pickupState: "Pahang",
                  },
                ]
        401:
          description: "Unauthorized Responses result"
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Unauthorized"
              message: "Secret key must be provided"

  /v1/partner/track/:
    x-summary: Tracking
    post:
      description: >-
        Tracking order.
      summary: POST
      parameters:
        - name: token
          in: header
          description: a account secret
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/TrackOrderRequest"
      responses:
        200:
          description: "Successfully Responses result"
          schema:
            $ref: "#/definitions/TrackOrder"
          examples:
            application/json:
              ninjavan:
                [
                  {
                    consign_no: "NVMYAXVEL000001063",
                    serviceProvider: "ninjavan",
                    status: "Waiting Pickup",
                    lastUpdateStatus: "2021-04-20T10:14:06.476Z",
                  },
                ]
        401:
          description: "Unauthorized Responses result"
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Unauthorized"
              message: "Secret key must be provided"

  /v1/partner/consign-pdf/:
    x-summary: Download Consignment Note
    post:
      description: >-
        Download the consignment note through signed URL. The signed URL will be expired upon visiting.
      summary: POST
      parameters:
        - name: token
          in: header
          description: a account secret
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/DownloadConnoteRequest"
      responses:
        200:
          description: "Successfully Responses result"
          # schema:
          #   $ref: '#/definitions/DownloadConnote'
          # examples:
          #   application/json:
          #       ninjavan: [
          #         {
          #           consign_no: "NVMYAXVEL000001063",
          #           serviceProvider: "ninjavan",
          #           status: "Waiting Pickup",
          #           lastUpdateStatus: "2021-04-20T10:14:06.476Z"
          #         }
          #       ]
        401:
          description: "Unauthorized Responses result"
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Unauthorized"
              message: "Secret key must be provided"

  /v1/partner/flashNotify/:
    x-summary: Notify Flash Courier
    post:
      description: >-
        Notify flash courier to pickup the parcel.
      summary: POST
      parameters:
        - name: token
          in: header
          description: a account secret
          required: true
          type: string
        - name: merchantid
          in: header
          description: a account id
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/FlashNotifyResponse"
      responses:
        200:
          description: "Successfully Responses result"
          schema:
            $ref: "#/definitions/FlashNotify"
          examples:
            application/json:
              order:
                {
                  code: 1,
                  message: "success",
                  data:
                    {
                      ticketPickupID: 192508,
                      staffInfoId: 121890,
                      staffInfoName: "Badrul",
                      staffInfoPhone: "0174121412",
                      upCountryNote: null,
                      timeoutAtText: "tomorrow 14:00 ~ 16:00",
                      ticketMessage: "The courier may not be able to arrive on time",
                      notice: null,
                    },
                }

        401:
          description: "Unauthorized Responses result"
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Unauthorized"
              message: "Secret key must be provided"

  /v1/partner/getpl9:
    x-summary: Download PL9 form
    get:
      description: |
        Download the PL9 form through signed URL. The signed URL will be expired upon visiting.

        _**NOTE**_: Please take note that the user need to have one **`PL9 form`** when have poslaju parcel pickup and it's only available for _**production**_
      summary: GET
      parameters:
        - name: token
          in: header
          description: a account secret
          required: true
          type: string
        - name: merchantid
          in: header
          description: a account id
          required: true
          type: string
      responses:
        200:
          description: "Successfully Responses result"
        401:
          description: "Unauthorized Responses result"
          schema:
            $ref: "#/definitions/Error"
          examples:
            application/json:
              error: "Unauthorized"
              message: "Secret key must be provided"

definitions:
  Postcode:
    title: Postcode
    type: object
    properties:
      success:
        type: object
        properties:
          ok:
            type: string
            description: >-
              Result correct
          state:
            type: string
            description: >-
              Malaysia state
  PostcodeRequest:
    title: Postcode Request
    type: object
    properties:
      postcode:
        type: string
        example: "25200"
        description: |
          * Must be valid postcode
          * Postcode is based on country
      country:
        type: string
        example: "Malaysia"
        description: |
          Country Name
          * Currently support **Malaysia** and **Singapore**
    required:
      - postcode
      - country
    example:
      postcode: "25200"
      country: "Malaysia"

  Quote:
    title: Quote
    type: object
    properties:
      success:
        type: object
        properties:
          fromoPostcode:
            type: object
            properties:
              Postcode:
                type: string
                description: >-
                  Malaysia postcode
              Place:
                type: string
                description: >-
                  Name of place
              Area:
                type: string
                description: >-
                  Name of city
              State:
                type: string
                description: >-
                  Short name of state
              StateName:
                type: string
                description: >-
                  Name of state
          toPostcode:
            type: object
            properties:
              Postcode:
                type: string
                description: >-
                  Malaysia postcode
              Place:
                type: string
                description: >-
                  Name of place
              Area:
                type: string
                description: >-
                  Name of city
              State:
                type: string
                description: >-
                  Short name of state
              StateName:
                type: string
                description: >-
                  Name of state
          poslajuPrice:
            type: string
            description: >-
              Total Price for poslaju
          poslajuPostage:
            type: string
            description: >-
              Price for poslaju
          cod:
            type: string
            description: >-
              COD price
          notificationRate:
            type: string
            description: >-
              Notification price
          dhlPostage:
            type: string
            description: >-
              Price for DHL
          dhlCod:
            type: string
            description: >-
              Price DHL charge for COD
          dhlInsurance:
            type: string
            description: >-
              Price DHL charge for insurance
          dhlPrice:
            type: string
            description: >-
              Total Price for DHL
          ninjavanPostage:
            type: string
            description: >-
              Price for ninjavan
          ninjavanCod:
            type: string
            description: >-
              Price ninjavan charge for COD
          ninjavanInsurance:
            type: string
            description: >-
              Price ninjavan charge for insurance
          ninjavanPrice:
            type: string
            description: >-
              Total price for ninjavan
          jntPostage:
            type: string
            description: >-
              Price for J&T
          jntCod:
            type: string
            description: >-
              Price J&T charge for COD
          jntInsurance:
            type: string
            description: >-
              Price J&T charge for insurance
          jntPrice:
            type: string
            description: >-
              Total price for J&T
          citylinkPostage:
            type: string
            description: >-
              Price for citylink
          citylinkPrice:
            type: string
            description: >-
              Total Price for citylink
          pickuppPostage:
            type: string
            description: >-
              Price for Pickupp
          pickuppCod:
            type: string
            description: >-
              Price Pickupp charge for COD
          pickuppPrice:
            type: string
            description: >-
              Total price for Pickupp
          teleportPostage:
            type: string
            description: >-
              Price for Teleport
          teleportCod:
            type: string
            description: >-
              Price Teleport charge for COD
          teleportPrice:
            type: string
            description: >-
              Total price for Teleport
          sfstandardPostage:
            type: string
            description: >-
              Price for SF Standard
          sfstandardPrice:
            type: string
            description: >-
              Total price for SF Standard
          sfeconomyPostage:
            type: string
            description: >-
              Price for SF Economy
          sfeconomyPrice:
            type: string
            description: >-
              Total price for SF Economy
          flashPostage:
            type: string
            description: >-
              Price for Flash
          flashCod:
            type: string
            description: >-
              Price Flash charge for COD
          flashPrice:
            type: string
            description: >-
              Total price for Flash
  QuoteRequest:
    title: Quote Request
    type: object
    properties:
      origin:
        type: integer
        example: 25200
        description: |
          Postcode from destination
          * Must be valid postcode
          * Postcode is based on country
      destination:
        type: integer
        example: 25200
        description: |
          Postcode to destination
          * Must be valid postcode
          * Postcode is based on country
      weight:
        type: integer
        maximum: 30
        description: |
          Weight of parcel
      cod:
        type: integer
        maximum: 4000
        description: |
          Cash On Delivery Price 
          * Only available for **DHL**, **Ninjavan**, **J&T** and **Flash**
      insurance:
        type: integer
        minimum: 201
        maximum: 2000
        description: |
          Insurance value for the parcel 
          * Only available for **DHL** , **Ninjavan** and **JNT**
      originCountry:
        type: string
        example: Malaysia
        description: |
          From country
          * Currently support **Malaysia** and **Singapore**
      destinationCountry:
        type: string
        example: Malaysia
        description: |
          Destination country
          * Currently support **Malaysia** and **Singapore**
    required:
      - origin
      - originCountry
      - destination
      - destinationCountry
      - weight
    example:
      origin: 25200
      destination: 25200
      weight: 2
      cod: 0
      originCountry: "Malaysia"
      destinationCountry: "Malaysia"

  CreateOrder:
    title: Create Order
    type: object
    properties:
      success:
        type: object
        properties:
          serviceProvider:
            type: string
            description: |
              Type of parcel
          merchant:
            type: object
            description: |
              Merchant info
          price:
            type: integer
            description: |
              Total Price
          content_value:
            type: string
            description: |
              Value of parcel
          receiver:
            type: object
            description: |
              Receiver info
          content:
            type: string
            description: |
              Parcel discription
          kg:
            type: integer
            description: |
              Weight of parcel
          cod:
            type: string
            description: |
              COD price
          pickup:
            type: object
            description: |
              Pickup info
          createAt:
            type: string
            description: |
              Datetime of parcel created
          updateAt:
            type: string
            description: |
              Datetime of parcel created
          objectId:
            type: string
            description: |
              Order ID
  CreateOrderRequest:
    title: Create Order Request
    type: object
    properties:
      serviceProvider:
        type: string
        example: |
          dhl
        description: |
          Type of parcel that support is:
          * dhl
          * poslaju
          * ninjavan
          * citylink
          * jnt
          * pickupp
          * teleport
          * sfstandard
          * sfeconomy
          * flash
      pickupAddress:
        type: object
        description: >-
          Sender Address
        properties:
          fullName:
            type: string
            minLength: 3
            example: Sam
            description: |
              Sender name
          countryCode:
            type: string
            example: "+6"
            description: |
              Sender country code. Currently support **Malaysia** and **Singapore** 
              * If Malaysian, country code is **+6**
              * If Singapore, country code is **+65**
          phone:
            type: string
            minLength: 9
            maxLength: 10
            example: "171425324"
            description: |
              Sender Phone number
          email:
            type: string
            format: email
            example: sender@test.com
            description: |
              Sender email
              * Must be valid email address
          line1:
            type: string
            maxLength: 50
            example: No.1, Lorong A
            description: >-
              Sender Line 1 Address
          line2:
            type: string
            maxLength: 50
            example: Taman A
            description: >-
              Sender Line 2 Address
          city:
            type: string
            example: Kuantan
            description: |
              Sender City Address
          postcode:
            type: string
            example: "25200"
            description: |
              Sender Postcode Address 
              * Must be valid postcode
              * Postcode is based on country
          state:
            type: string
            example: Pahang
            description: |
              Sender State Address
              * State is based on country
          country:
            type: string
            example: Malaysia
            description: |
              Sender country
              * Currently support **Malaysia** and **Singapore**

        required:
          - fullName
          - countryCode
          - phone
          - email
          - line1
          - line2
          - city
          - postcode
          - state
          - country
      clientAddress:
        type: object
        description: >-
          Receiver Address id
        properties:
          fullName:
            type: string
            minLength: 3
            example: Mex
            description: |
              Receiver name
          countryCode:
            type: string
            example: "+6"
            description: |
              Receiver country code. Currently support **Malaysia** and **Singapore** 
              * If Malaysian, country code is **+6**
              * If Singapore, country code is **+65**
          phone:
            type: string
            minLength: 9
            maxLength: 10
            example: "171425324"
            description: |
              Receiver Phone number
          email:
            type: string
            format: email
            example: receiver@test.com
            description: |
              Receiver email
              * Must be valid email address
          line1:
            type: string
            maxLength: 50
            example: No.1, Lorong B
            description: >-
              Receiver Line 1 Address
          line2:
            type: string
            maxLength: 50
            example: Taman B
            description: >-
              Receiver Line 2 Address
          city:
            type: string
            example: Kuantan
            description: |
              Receiver City Address
          postcode:
            type: string
            example: "25200"
            description: |
              Receiver Postcode Address
              * Must be valid postcode
              * Postcode is based on country
          state:
            type: string
            example: Pahang
            description: |
              Receiver State Address
              * State is based on country
          country:
            type: string
            example: Malaysia
            description: |
              Receiver country
              * Currently support **Malaysia** and **Singapore**

        required:
          - fullName
          - phon
          - email
          - line1
          - line2
          - city
          - postcode
          - state
      kg:
        type: integer
        description: |
          Weight of parcel
      insurance:
        type: integer
        minimum: 201
        maximum: 2000
        description: |
          Insurance value for the parcel 
          * Only available for **DHL** , **Ninjavan** and **JNT**
      price:
        type: integer
        description: >-
          Get the price from quotation api
      content:
        type: string
        maxLength: 50
        example: book
        description: |
          Pracel detail description
      content_value:
        type: integer
        description: >-
          Parcel detail value
      commodity_id:
        type: integer
        description: |
          Parcel commudity_id value. Can refer the id by click [here](https://www.foreign-trade.com/reference/hscode.htm)
          * Only required for **Teleport** and **SF**
      cod:
        type: integer
        description: |
          Cash On Delivery Price
          * Only available for **DHL** , **Ninjavan**, **J&T** and **Flash**
      isDropoff:
        type: boolean
        description: |
          Boolean flag that indicates whether or not a drop off is required. 
          If **false**, the order will be picked up and the sender's address will be used as the pickup address.
          * Only available for **Poslaju** , **DHL** , **Ninjavan** and **J&T**
    required:
      - serviceProvider
      - pickupAddress
      - clientAddress
      - kg
      - price
      - content
      - content_value
      - isDropoff
    example:
      serviceProvider: "dhl"
      pickupAddress:
        fullName: "Sam"
        countryCode: "+6"
        phone: "171414521"
        email: "sender@test.com"
        line1: "No.1, Lorong A"
        line2: "Taman A"
        city: "Kuantan"
        postcode: "25200"
        state: "Pahang"
        country: "Malaysia"
      clientAddress:
        fullName: "Mex"
        countryCode: "+6"
        phone: "171414521"
        email: "receiver@test.com"
        line1: "No.1, Lorong B"
        line2: "Taman B"
        city: "Kuantan"
        postcode: "25200"
        state: "Pahang"
        country: "Malaysia"
      kg: 2
      price: 6.5
      commodity_id: 1006
      content: "Rice"
      content_value: 2
      isDropoff: false

  CreateBulkOrder:
    title: Create Bulk Order
    type: object
    properties:
      success:
        type: object
        properties:
          serviceProvider:
            type: string
            description: |
              Type of parcel
          merchant:
            type: object
            description: |
              Merchant info
          price:
            type: integer
            description: |
              Total Price
          content_value:
            type: string
            description: |
              Value of parcel
          receiver:
            type: object
            description: |
              Receiver info
          content:
            type: string
            description: |
              Parcel discription
          kg:
            type: integer
            description: |
              Weight of parcel
          cod:
            type: string
            description: |
              COD price
          pickup:
            type: object
            description: |
              Pickup info
          createAt:
            type: string
            description: |
              Datetime of parcel created
          updateAt:
            type: string
            description: |
              Datetime of parcel created
          objectId:
            type: string
            description: |
              Order ID
  CreateBulkOrderRequest:
    title: Create Bulk Order Request
    type: object
    properties:
      orders:
        type: object
        properties:
          serviceProvider:
            type: string
            example: |
              dhl, poslaju, ninjavan, citylink, jnt
            description: |
              Type of parcel
          pickupAddress:
            type: object
            description: >-
              Sender Address
            properties:
              fullName:
                type: string
                minLength: 3
                example: Sam
                description: |
                  Sender name
              countryCode:
                type: string
                example: "+6"
                description: |
                  Sender country code. Currently support **Malaysia** and **Singapore**
                  * If Malaysian, country code is **+6**
                  * If Singapore, country code is **+65**
              phone:
                type: string
                minLength: 9
                maxLength: 10
                example: "171425324"
                description: |
                  Sender Phone number
              email:
                type: string
                format: email
                example: sender@test.com
                description: |
                  Sender email
                  * Must be valid email address
              line1:
                type: string
                maxLength: 50
                example: No.1, Lorong A
                description: >-
                  Sender Line 1 Address
              line2:
                type: string
                maxLength: 50
                example: Taman A
                description: >-
                  Sender Line 2 Address
              city:
                type: string
                example: Kuantan
                description: |
                  Sender CIty Address
              postcode:
                type: string
                example: "25200"
                description: |
                  Sender Postcode Address 
                  * Must be valid postcode
                  * Postcode is based on country
              state:
                type: string
                example: Pahang
                description: |
                  Sender State Address 
                  * State is based on country
              country:
                type: string
                example: Malaysia
                description: |
                  Sender country
                  * Currently support **Malaysia** and **Singapore**

            required:
              - fullName
              - countryCode
              - phone
              - email
              - line1
              - line2
              - city
              - postcode
              - state
              - country
          clientAddress:
            type: object
            description: >-
              Receiver Address id
            properties:
              fullName:
                type: string
                minLength: 3
                example: Mex
                description: |
                  Receiver name
              countryCode:
                type: string
                example: "+6"
                description: |
                  Receiver country code. Currently support **Malaysia** and **Singapore** 
                  * If Malaysian, country code is **+6**
                  * If Singapore, country code is **+65**
              phone:
                type: string
                minLength: 9
                maxLength: 10
                example: "171425324"
                description: |
                  Receiver Phone number
              email:
                type: string
                format: email
                example: receiver@test.com
                description: |
                  Receiver email
                  * Must be valid email address
              line1:
                type: string
                maxLength: 50
                example: No.1, Lorong B
                description: >-
                  Receiver Line 1 Address
              line2:
                type: string
                maxLength: 50
                example: Taman B
                description: >-
                  Receiver Line 2 Address
              city:
                type: string
                example: Kuantan
                description: |
                  Receiver CIty Address
              postcode:
                type: string
                example: "25200"
                description: |
                  Receiver Postcode Address
                  * Must be valid postcode
                  * Postcode is based on country
              state:
                type: string
                example: Pahang
                description: |
                  Receiver State Address
                  * State is based on country
              country:
                type: string
                example: Malaysia
                description: |
                  Receiver country
                  * Currently support **Malaysia** and **Singapore**

            required:
              - fullName
              - countryCode
              - phone
              - email
              - line1
              - line2
              - city
              - postcode
              - state
              - country
          kg:
            type: integer
            description: |
              Weight of parcel
          insurance:
            type: integer
            minimum: 201
            maximum: 2000
            description: |
              Insurance value for the parcel 
              * Only available for **DHL** , **Ninjavan** and **JNT**
          price:
            type: integer
            description: >-
              Get the price from quotation api
          content:
            type: string
            maxLength: 50
            example: book
            description: |
              Pracel detail description
          content_value:
            type: integer
            description: >-
              Parcel detail value
          commodity_id:
            type: integer
            description: |
              Parcel commudity_id value. Can refer the id by click [here](https://www.foreign-trade.com/reference/hscode.htm)
              * Only required for **Teleport** and **SF**
          cod:
            type: integer
            description: |
              Cash On Delivery Price
              * Only available for **DHL** , **Ninjavan**, **J&T** and **Flash**
          isDropoff:
            type: boolean
            description: |
              Boolean flag that indicates whether or not a drop off is required. 
              If **false**, the order will be picked up and the sender's address will be used as the pickup address.
              * Only available for **Poslaju** , **DHL** , **Ninjavan** and **J&T**
        required:
          - serviceProvider
          - pickupAddress
          - clientAddress
          - kg
          - price
          - content
          - content_value
          - isDropoff
    example:
      orders:
        [
          {
            serviceProvider: "dhl",
            pickupAddress:
              {
                fullName: "Sam",
                countryCode: "+6",
                phone: "171414521",
                email: "sender@test.com",
                line1: "No.1, Lorong A",
                line2: "Taman A",
                city: "Kuantan",
                postcode: "25200",
                state: "Pahang",
                country: "Malaysia",
              },
            clientAddress:
              {
                fullName: "Mex",
                countryCode: "+6",
                phone: "171414521",
                email: "receiver@test.com",
                line1: "No.1, Lorong B",
                line2: "Taman B",
                city: "Kuantan",
                postcode: "25200",
                state: "Pahang",
                country: "Malaysia",
              },
            kg: 2,
            price: 6.5,
            commodity_id: 1006,
            content: "Rice",
            content_value: 2,
            isDropoff: false,
          },
        ]

  PayOrder:
    title: Pay All Order
    type: object
    properties:
      success:
        type: array
        description: >-
          List of order id that successfully pay
  PayOrderRequest:
    title: Get All Order Request
    type: object
    properties:
      orderIds:
        type: array
        description: >-
          Order Id that want to make purchase
    required:
      - orderIds
    example:
      orderIds: [sfMeOuzvtK]

  TrackOrder:
    title: Track Order
    type: object
    properties:
      ninjavan:
        type: array
        description: >-
          Parcel type
        items:
          type: object
          properties:
            consign_no:
              type: string
              description: >-
                Consignment number of tracking
            serviceProvider:
              type: string
              description: >-
                Type of parcel
            status:
              type: string
              description: >-
                Parcel status
            lastUpdatesStatus:
              type: string
              description: >-
                Datetime for updated parcel status
  TrackOrderRequest:
    title: Track Order Request
    type: object
    properties:
      connote:
        type: string
        example: NVMYAXVEL000001063
        description: >-
          Parcel tracking number
    required:
      - connote
    example:
      connote: NVMYAXVEL000001063

  DownloadConnote:
    title: Download Connote
    type: object
    # properties:
    #   connote:
    #     type: string
    # required:
    #   - connote
  DownloadConnoteRequest:
    title: Download Connote Request
    type: object
    properties:
      connote:
        type: string
        description: >-
          Parcel tracking number
    required:
      - connote
    example:
      connote: NVMYAXVEL000001063

  FlashNotify:
    title: Flash Notify Response
    type: object
    properties:
      orders:
        type: object
        description: >-
          Response detail
        properties:
          code:
            type: string
            description: >-
              Response code
          message:
            type: string
            description: >-
              Response message
          data:
            type: object
            description: >-
              Pickup info
            properties:
              ticketPickupId:
                type: string
                description: >-
                  Pickup ID
              staffInfoId:
                type: string
                description: >-
                  Driver ID
              staffInfoName:
                type: string
                description: >-
                  Drive name
              staffInfoPhone:
                type: string
                description: >-
                  Drive phone number
              upCountryNote:
                type: string
                description: >-
                  Country note from flash courier
              timeoutAtText:
                type: string
                description: >-
                  Time for flash courier pickup
              ticketMessage:
                type: string
                description: >-
                  Message from flash courier
              notice:
                type: string
                description: >-
                  Notice
  FlashNotifyResponse:
    title: Flash Notify Request
    type: object
    properties:
      name:
        type: string
        example: Ali
        description: >-
          Pickup location contact name
      phone:
        type: string
        example: "+60174547414"
        description: >-
          Pickup location contact name number
      addressLine:
        type: string
        example: Unit A-28-03, Aurora Residences
        description: >-
          Pickup location detail address
      postcode:
        type: string
        example: "47150"
        description: >-
          Pickup location postcode
      city:
        type: string
        example: Puchong
        description: >-
          Pickup location city
      state:
        type: string
        example: Selangor
        description: >-
          Pickup location state
      quantity:
        type: number
        example: 1
        description: >-
          Estimated parcels quantity to pickup
      remark:
        type: string
        example: Call when arrive
        description: >-
          Remark
    required:
      - name
      - phone
      - addressLine
      - postcode
      - city
      - state
      - quantity
      - remark
    example:
      name: Ali
      phone: "+60174547414"
      addressLine: Unit A-28-03, Aurora Residences
      postcode: 47150
      city: Puchong
      state: Selangor
      quantity: 2
      remark: Call when arrive

  Error:
    type: object
    properties:
      error:
        type: string
        description: >-
          Type of errorr
      message:
        type: string
        description: >-
          Error message

  ErrorEmpty:
    type: object
    properties:
      error:
        type: object
        description: >-
          Attribute that contain error
        properties:
          destination:
            type: array
            items:
              type: string
              description: >-
                Error message
